name: GitHub Breakout

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Cada nível aqui tem dois espaços a mais que o anterior
      - uses: actions/checkout@v2

      - uses: cyprieng/github-breakout@90be7fe2a0909a65dfae356079298bce401094e0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update github-breakout svgs"
          file_pattern: "*.svg"
